### PR TITLE
Added a submodule for the John Hopkins COVID-19 data.

### PR DESCRIPTION
**Pull request by gigatar**
Created a sub-module dependency for the John Hopkins data and updated the readme with information on how to update the submodule.

### CODE REVIEW

**Comment by fdesantis2855** [comment]
Please update the module.  I'll pull it after.

**Comment by fdesantis2855** [comment]
Please update the sub module.   Before I update the pull request

**Comment by fdesantis2855** [comment]
Reopened... please review previous message

**Comment by gigatar** [comment]
Data is already up-to-date.

**Pull request merged**
